from __future__ import annotations

import re
import difflib
import threading
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from app.core.config import get_settings
from app.schemas.notes_common import NotesResult
from app.services.notes_audit import record_note_action
from app.services.notes_repository import (
    NotesRepositoryError,
    atomic_write,
    calculate_sha256,
    get_baseline_commit,
    parse_frontmatter,
    render_note,
    resolve_review_path,
)


JARVIS_CALLOUT = (
    "> [!warning] Jarvis-written draft\n"
    "> This note was generated by Jarvis and has not yet been reviewed."
)
_WRITE_LOCK = threading.RLock()


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _attributed_content(
    *,
    title: str,
    body: str,
    existing_frontmatter: dict[str, Any] | None = None,
    sources: list[str] | None = None,
    generation_run: str | None = None,
) -> str:
    metadata = dict(existing_frontmatter or {})
    timestamp = _now()
    metadata.update(
        {
            "title": title,
            "status": "draft",
            "authorship": "ai-generated",
            "created_by": "jarvis",
            "review_status": "pending",
            "updated": timestamp,
            "source_revision": get_baseline_commit(),
        }
    )
    metadata.setdefault("created", timestamp)
    metadata["sources"] = sources if sources is not None else metadata.get("sources", [])
    if generation_run is not None:
        metadata["generation_run"] = generation_run
    tags = metadata.get("tags", [])
    if not isinstance(tags, list):
        tags = [str(tags)]
    metadata["tags"] = list(dict.fromkeys([*tags, "jarvis-written", "pending-review"]))
    clean_body = body.strip()
    if JARVIS_CALLOUT not in clean_body:
        clean_body = f"{JARVIS_CALLOUT}\n\n{clean_body}"
    return render_note(metadata, clean_body)


def _git_diff_summary(path: Path) -> dict[str, Any]:
    settings = get_settings()
    review_root = settings.notes_review_root
    baseline_root = settings.notes_baseline_root
    if review_root is None or baseline_root is None:
        return {}
    relative = path.relative_to(review_root.resolve())
    baseline_path = baseline_root.resolve() / relative
    try:
        before = baseline_path.read_text(encoding="utf-8").splitlines() if baseline_path.is_file() else []
        after = path.read_text(encoding="utf-8").splitlines()
    except OSError:
        return {}
    diff = list(difflib.unified_diff(before, after, fromfile=f"baseline/{relative}", tofile=f"review/{relative}", lineterm=""))
    added = sum(1 for line in diff if line.startswith("+") and not line.startswith("+++"))
    removed = sum(1 for line in diff if line.startswith("-") and not line.startswith("---"))
    return {
        "status": "modified" if baseline_path.is_file() else "untracked",
        "added_lines": added,
        "removed_lines": removed,
        "diff": "\n".join(diff[:400]),
        "truncated": len(diff) > 400,
    }


def _replace_section(body: str, heading: str, replacement: str) -> str:
    matches = list(re.finditer(rf"^(#{{1,6}})\s+{re.escape(heading)}\s*$", body, re.MULTILINE))
    if not matches:
        raise NotesRepositoryError(f"Heading not found: {heading}", "NOT_FOUND")
    if len(matches) > 1:
        raise NotesRepositoryError(f"Heading is ambiguous: {heading}", "AMBIGUOUS_HEADING")
    match = matches[0]
    level = len(match.group(1))
    next_heading = re.search(rf"^#{{1,{level}}}\s+", body[match.end():], re.MULTILINE)
    end = match.end() + next_heading.start() if next_heading else len(body)
    return f"{body[:match.end()]}\n\n{replacement.strip()}\n\n{body[end:].lstrip()}".rstrip()


def _notes_write(
    operation: str,
    *,
    path: str,
    title: str | None = None,
    content: str | None = None,
    heading: str | None = None,
    expected_hash: str | None = None,
    sources: list[str] | None = None,
    generation_run: str | None = None,
) -> NotesResult:
    baseline_commit: str | None = None
    before_hash: str | None = None
    try:
        baseline_commit = get_baseline_commit()
        target = resolve_review_path(path)
        exists = target.is_file()
        if target.exists() and not exists:
            raise NotesRepositoryError("The target exists but is not a regular file.", "INVALID_PATH")

        if operation == "create":
            if exists:
                return NotesResult("conflict", operation, baseline_commit, path, error_code="ALREADY_EXISTS", message="Draft already exists.")
            if not title or content is None:
                raise NotesRepositoryError("create requires title and content.", "INVALID_INPUT")
            rendered = _attributed_content(title=title, body=content, sources=sources, generation_run=generation_run)
        elif operation in {"replace_draft", "append", "update_section"}:
            if not exists:
                return NotesResult("not_found", operation, baseline_commit, path, error_code="NOT_FOUND", message="Draft not found.")
            before_hash = calculate_sha256(target)
            if expected_hash is not None and expected_hash != before_hash:
                return NotesResult("conflict", operation, baseline_commit, path, error_code="CONTENT_CONFLICT", message="The draft changed after it was read.")
            raw = target.read_text(encoding="utf-8")
            metadata, body = parse_frontmatter(raw)
            if metadata.get("created_by") != "jarvis":
                raise NotesRepositoryError("Only Jarvis-authored drafts may be modified.", "NOT_JARVIS_DRAFT")
            note_title = title or str(metadata.get("title") or target.stem)
            if operation == "replace_draft":
                if expected_hash is None:
                    raise NotesRepositoryError("replace_draft requires expected_hash.", "EXPECTED_HASH_REQUIRED")
                if content is None:
                    raise NotesRepositoryError("replace_draft requires content.", "INVALID_INPUT")
                new_body = content
            elif operation == "append":
                if content is None:
                    raise NotesRepositoryError("append requires content.", "INVALID_INPUT")
                new_body = f"{body.rstrip()}\n\n{content.strip()}"
            else:
                if expected_hash is None:
                    raise NotesRepositoryError("update_section requires expected_hash.", "EXPECTED_HASH_REQUIRED")
                if not heading or content is None:
                    raise NotesRepositoryError("update_section requires heading and content.", "INVALID_INPUT")
                new_body = _replace_section(body, heading, content)
            rendered = _attributed_content(
                title=note_title,
                body=new_body,
                existing_frontmatter=metadata,
                sources=sources,
                generation_run=generation_run,
            )
        else:
            raise NotesRepositoryError(f"Unsupported write operation: {operation}", "INVALID_OPERATION")

        atomic_write(target, rendered)
        after_hash = calculate_sha256(target)
        data = {
            "before_hash": before_hash,
            "after_hash": after_hash,
            "review_status": "pending",
            "git": _git_diff_summary(target),
        }
        record_note_action(
            {
                "operation": operation,
                "path": path,
                "baseline_commit": baseline_commit,
                "before_hash": before_hash,
                "after_hash": after_hash,
                "status": "success",
                "generation_run": generation_run,
            }
        )
        return NotesResult("success", operation, baseline_commit, path, changed=True, data=data, message="Draft written for human review; no Git commit was created.")
    except (NotesRepositoryError, OSError) as exc:
        code = exc.error_code if isinstance(exc, NotesRepositoryError) else "FAILED"
        status = "refused" if isinstance(exc, NotesRepositoryError) else "failed"
        record_note_action(
            {
                "operation": operation,
                "path": path,
                "baseline_commit": baseline_commit,
                "before_hash": before_hash,
                "status": status,
                "error_code": code,
            }
        )
        return NotesResult(status, operation, baseline_commit, path, error_code=code, message=str(exc))


def notes_write(
    operation: str,
    *,
    path: str,
    title: str | None = None,
    content: str | None = None,
    heading: str | None = None,
    expected_hash: str | None = None,
    sources: list[str] | None = None,
    generation_run: str | None = None,
) -> NotesResult:
    # Serialize compare-and-write operations inside this service process so the
    # expected-hash check and atomic replacement behave as one unit.
    with _WRITE_LOCK:
        return _notes_write(
            operation,
            path=path,
            title=title,
            content=content,
            heading=heading,
            expected_hash=expected_hash,
            sources=sources,
            generation_run=generation_run,
        )
